name: Build and Release Electron Vue App

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]
    types: [closed]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    environment: app
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm run test
